run:
  timeout: 15m

output:
  sort-results: true

linters:
  enable:
    - depguard
    - errorlint
    - gocritic
    - godot
    - gofumpt
    - goimports
    - misspell
    - nolintlint
    - perfsprint
    - predeclared
    - revive
    - testifylint
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
    - loggercheck

issues:
  max-same-issues: 0
  exclude-files:
    - ^.*\.(pb|y)\.go$
  exclude-dirs:
    - tests
    - examples
    - docs
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "sync/atomic"
            desc: "Use go.uber.org/atomic instead of sync/atomic"
          - pkg: "github.com/stretchr/testify/assert"
            desc: "Use github.com/stretchr/testify/require instead of github.com/stretchr/testify/assert"
          - pkg: "github.com/go-kit/kit/log"
            desc: "Use github.com/go-kit/log instead of github.com/go-kit/kit/log"
          - pkg: "io/ioutil"
            desc: "Use corresponding 'os' or 'io' functions instead."
          - pkg: "regexp"
            desc: "Use github.com/grafana/regexp instead of regexp"
          - pkg: "github.com/pkg/errors"
            desc: "Use 'errors' or 'fmt' instead of github.com/pkg/errors"
          - pkg: "gzip"
            desc: "Use github.com/klauspost/compress instead of gzip"
          - pkg: "zlib"
            desc: "Use github.com/klauspost/compress instead of zlib"
          - pkg: "golang.org/x/exp/slices"
            desc: "Use 'slices' instead."
  errcheck:
    exclude-functions:
      - io.Copy
      - io.WriteString
      - (net/http.ResponseWriter).Write
      - (*net/http.Server).Shutdown
  goimports:
    local-prefixes: github.com/rppkg/godfrey
  gofumpt:
    extra-rules: true
  perfsprint:
    errorf: false
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
        arguments:
          - allowTypesBefore: "*testing.T,testing.TB"
      - name: context-keys-type
      - name: dot-imports
      - name: empty-block
        disabled: true
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-naming
      - name: unexported-return
      - name: unreachable-code
      - name: unused-parameter
        disabled: true
      - name: var-declaration
      - name: var-naming
  testifylint:
    disable:
      - float-compare
      - go-require
    enable:
      - bool-compare
      - compares
      - empty
      - error-is-as
      - error-nil
      - expected-actual
      - len
      - require-error
      - suite-dont-use-pkg
      - suite-extra-assert-call
